version: '3.4'

services:
  travel_postgresql:
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "45432:5432"
    networks:
      - shared_travel_net
    volumes:      
      - ~/.docker-conf/postgresql/data/:/var/lib/postgresql/data

  travel_api:
    ports:
      - "10000:8080"
    networks:
      - shared_travel_net
    env_file:
      - env.api

  # travel_identity:
  #   ports:
  #     - "10001:8080"
  #   networks:
  #     - shared_travel_net
  #   env_file:
  #     - env.identity

networks:
  shared_travel_net:
    name: travel
    driver: bridge